#define MK_KINETIC_SPEED 2
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_BASE_SPEED 50
#define MOUSEKEY_DECELERATED_SPEED 100
#define MOUSEKEY_ACCELERATED_SPEED 100

#define RGBLIGHT_LAYERS

#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE
