#define MK_KINETIC_SPEED 5
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_BASE_SPEED 50
#define MOUSEKEY_DECELERATED_SPEED 100
#define MOUSEKEY_ACCELERATED_SPEED 100

#define RGBLIGHT_DEFAULT_MODE (RGBLIGHT_EFFECT_STATIC_GRADIENT + 3)
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_MODE_STATIC_GRADIENT 5
